[profile.default]
src = "contracts"
out = "out"
libs = ["lib", "node_modules"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/=node_modules/@openzeppelin/"
]

[rpc_endpoints]
didlab = "https://eth.didlab.org"
